name: Update v1.imba.io
on: [push]
jobs:

  deploy:
    name: Deploy v1
    if: github.ref == 'refs/heads/v1'
    runs-on: ubuntu-latest
    steps:
    - name: Connect to imba.io and run commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          git -C /home/imba/v1.imba.io checkout .
          git -C /home/imba/v1.imba.io pull origin v1
          cd /home/imba/v1.imba.io  && \
          /usr/bin/yarn install && \
          /usr/bin/yarn build
